# -*- coding: utf-8 -*-
"""SVM_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qwT0m0dbKE3GPCuE1o-RKRigWH7W5Bx
"""

import numpy as np
import pandas as pd

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

"""**Load MNIST Dataset**"""

from tensorflow.keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

"""**Preprocess Data**"""

X_train = X_train.reshape(60000, -1)
X_test = X_test.reshape(10000, -1)

X_train = X_train / 255.0
X_test = X_test / 255.0

svm_model = SVC(
    kernel='rbf',
    gamma='scale'
)

svm_model.fit(X_train, y_train)

"""**Prediction & Accuracy Output**"""

y_pred = svm_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("SVM Test Accuracy:", accuracy)